#!/bin/bash
# Update and install Apache (httpd)
sudo yum install -y httpd
sudo systemctl enable httpd

# Clean up default welcome page if it exists
if [ -f /var/www/html/index.html ]; then
    sudo rm -f /var/www/html/index.html
fi